author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = args.OPACK_PATH

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  To get started, run:")
    print(`     ${path}/mini-a.sh -jobhelp`)
    print("     (and set OAF_MODEL environment variable)")
    print()
    print("  Or set OAF_MODEL environment variable and then start the web interface with:")
    print(`     ${path}/mini-a-web.sh onport=12345`)
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: mini-a-main.yaml
license: Apache 2.0 license
version: '20251022'
dependencies:
  openaf: '>=20250915'
files:
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/mini-a-web-screenshot1.jpg
- .github/version.svg
- .github/workflows/github-action.yml
- .mcp-weather.pid
- .odoc.db
- .openaf_precompiled/.t8-20251020
- .openaf_precompiled/mini-a_js.class
- .package.yaml
- AGENTS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- TESTS_MODELS.md
- USAGE.md
- data.csv
- mcps/CREATING.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-file.yaml
- mcps/mcp-kube.yaml
- mcps/mcp-net.yaml
- mcps/mcp-oaf.yaml
- mcps/mcp-oafp.yaml
- mcps/mcp-random.yaml
- mcps/mcp-s3.yaml
- mcps/mcp-shell.yaml
- mcps/mcp-ssh.yaml
- mcps/mcp-time.yaml
- mcps/mcp-weather.yaml
- mini-a-file-tool.js
- mini-a-main.yaml
- mini-a-web.sh
- mini-a-web.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
- tests/advancedPlanning.js
- tests/advancedPlanning.yaml
- tests/autoTestAll.allJobs.yaml
- tests/autoTestAll.yaml
- tests/coreFunctionality.js
- tests/coreFunctionality.yaml
filesHash:
  .github/ISSUE_TEMPLATE/bug_report.md: 83d211c67c12e8c1f6e9f796cfd0cecbf5160e15
  .github/ISSUE_TEMPLATE/feature_request.md: f6867a2f0417fe89a0f2008730ee19dd38422021
  .github/mini-a-web-screenshot1.jpg: 20c5f09008868f9da2a982302426c243a6008ccc
  .github/version.svg: dca8c29e7fee6b1fdd80beb6fe5b09aad6635e2f
  .github/workflows/github-action.yml: 7e46f9c08b1107f59c7183400275197f7272e7af
  .mcp-weather.pid: 0346998e907878e4bde4f407ff7c3d1556352e44
  .odoc.db: c34866edd2a38fc05b81884dbdd56e083959f65a
  .openaf_precompiled/.t8-20251020: da39a3ee5e6b4b0d3255bfef95601890afd80709
  .openaf_precompiled/mini-a_js.class: ecad060f35b097511ca974f31780fc033ffa20ae
  AGENTS.md: 7b6df1520b27dc3ef4e025a084452c62d0e1c1f9
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: d363719aece9628552ff5b49a10d88f896ac5bdf
  EXTERNAL-MCPS.md: 6b0e52f59e26f3f16ba8a89338c792f3a763f0b7
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: a238c3ce025f99283c2adab73533a49bb9c7df28
  TESTS_MODELS.md: c8e334b573b4231f58f9798be83178f23ea53635
  USAGE.md: dabd5781f195694e1f43f9175d2fbb4592fd6770
  data.csv: 710fea7fa08d4ee63778cad39c1661fdc351ee36
  mcps/CREATING.md: 9d426fb29d822f8da53da1f3bd3580f7ba770671
  mcps/README.md: 44e5ef574fceb1d426ee07480ab6fecc7d1e874a
  mcps/mcp-ch.yaml: 4f9c7c4529904a68cfe59bdc402b418d5b43ff0c
  mcps/mcp-db.yaml: aae81e65ae3543e5d54ee37cd55d0c13dc6e4c14
  mcps/mcp-email.yaml: d9dde29b03e7b8873f66a22476dc8ffd6619ce85
  mcps/mcp-file.yaml: 995249f68f27578648a6ced34957b872b62cd6e7
  mcps/mcp-kube.yaml: d9268fd33f64db8afc6a7012540a72a358ccc021
  mcps/mcp-net.yaml: 36b0e8ef74274819422453d6e76df4426f37a187
  mcps/mcp-oaf.yaml: 5495533600957931871ef9549e3a9cf16609c959
  mcps/mcp-oafp.yaml: 4e7ba7a9ca5cb3dc9faa456f0f58225c7a41602a
  mcps/mcp-random.yaml: ac2ee99722a6ae2baeb14e19d4f881ce03e369c4
  mcps/mcp-s3.yaml: 845a363c5ca9d291a1ab24dad80972b6651b1a29
  mcps/mcp-shell.yaml: ce8b702efa515b704720f0d4e73a0093c1e4b699
  mcps/mcp-ssh.yaml: 06f3c50811f9cf23e9442f62fad59a8ebdfcd1c9
  mcps/mcp-time.yaml: 5b75f2b73f7650f778f1e80309ba922b006c04f2
  mcps/mcp-weather.yaml: dd339672ebcd6094e8f2ef87fc32a6d95b53bc68
  mini-a-file-tool.js: 2c2981d1bfee062ba8d8fe10ca3006a37aeaa711
  mini-a-main.yaml: eb36f5a6749500c7bef073059abf461916174aed
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: 92448c86ca5114b90b8811685187cabae5152cf0
  mini-a.js: b0247906077c167ca19a872e74037730981c422c
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: c02780a1cec62b76c9fd6d6dcd92c15e4de49cc9
  public/index.md: 42e879c1b451ca3303722ac4574373072045671b
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
  tests/advancedPlanning.js: a6a8d03e4ebaaea66bfa5b61e5daf702f4909f6a
  tests/advancedPlanning.yaml: 9c8f4dcb3d3bba1eda4343dfe7eda1b80126f78b
  tests/autoTestAll.allJobs.yaml: 628921dcb7e35c58e8807cfcbaece93b60ce93ff
  tests/autoTestAll.yaml: f4d909c00e8dbbf507bb6341bf46dd2ceb6ea93d
  tests/coreFunctionality.js: b10c42a85394f0ad6f72cebcef540497349080d8
  tests/coreFunctionality.yaml: 0a656733b02a5a4f77139766e42eabddfc4a39ca
