author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: ''
license: Apache 2.0 license
version: '20250920'
dependencies:
  openaf: '>=20250915'
files:
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .package.yaml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- mcps/README.md
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-notify.yaml
- mini-a-web.yaml
- mini-a.js
- mini-a.yaml
- mini-a.yaml.old
- public/index.md
filesHash:
  .github/ISSUE_TEMPLATE/bug_report.md: 83d211c67c12e8c1f6e9f796cfd0cecbf5160e15
  .github/ISSUE_TEMPLATE/feature_request.md: f6867a2f0417fe89a0f2008730ee19dd38422021
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: 279d907bcbdcddf93716e208b90b683e53b9f83a
  EXTERNAL-MCPS.md: 0eca01e82e2b4f161d7d50463b0977ed31e4d8df
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 96eb82df76fab7475055e92efaeed81bce9bd016
  mcps/README.md: 66152fb9bcee901891ae39ac2b399e431aefe29f
  mcps/mcp-db.yaml: d90c78a038fa67b340531f86fdc6fccd47c9ce55
  mcps/mcp-email.yaml: 7d950981f900f390fe6f9cd4d850453b288ec490
  mcps/mcp-notify.yaml: 01743e02dbb9b2873316b4d958c4d1433b6bf25a
  mini-a-web.yaml: 0f21bbfb4f41789cff8d33e9f0be41f1c30f3842
  mini-a.js: d47615cf230f34105913b783befb1e12d30f5e8d
  mini-a.yaml: 4c407b5396e744a50cde91581b5a30d228aca8a6
  mini-a.yaml.old: 07258d8c93b223b49def75de2a3ab44c21f2ea5c
  public/index.md: 9b4cf6d9aaa5f8d4a2b9eebfe18f5d6e2f03828c
