author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = args.OPACK_PATH

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  To get started, run:")
    print(`     ${path}/mini-a.sh -jobhelp`)
    print("     (and set OAF_MODEL environment variable)")
    print()
    print("  Or set OAF_MODEL environment variable and then start the web interface with:")
    print(`     ${path}/mini-a-web.sh onport=12345`)
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: mini-a-main.yaml
license: Apache 2.0 license
version: '20251027'
dependencies:
  openaf: '>=20250915'
files:
- .odoc.db
- .package.yaml
- AGENTS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- TESTS_MODELS.md
- USAGE.md
- examples/README.md
- examples/summary.yaml
- mcps/CREATING.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-file.yaml
- mcps/mcp-fin.yaml
- mcps/mcp-kube.yaml
- mcps/mcp-net.yaml
- mcps/mcp-oaf.yaml
- mcps/mcp-oafp.yaml
- mcps/mcp-random.yaml
- mcps/mcp-rss.yaml
- mcps/mcp-s3.yaml
- mcps/mcp-shell.yaml
- mcps/mcp-ssh.yaml
- mcps/mcp-time.yaml
- mcps/mcp-weather.yaml
- mini-a-file-tool.js
- mini-a-main.yaml
- mini-a-web.sh
- mini-a-web.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
- tests/advancedPlanning.js
- tests/advancedPlanning.yaml
- tests/autoTestAll.allJobs.yaml
- tests/autoTestAll.yaml
- tests/coreFunctionality.js
- tests/coreFunctionality.yaml
filesHash:
  .odoc.db: c34866edd2a38fc05b81884dbdd56e083959f65a
  AGENTS.md: 7b6df1520b27dc3ef4e025a084452c62d0e1c1f9
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: d363719aece9628552ff5b49a10d88f896ac5bdf
  EXTERNAL-MCPS.md: 6b0e52f59e26f3f16ba8a89338c792f3a763f0b7
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 17e33bea42db18943765776da8b62991aa5d5da5
  TESTS_MODELS.md: c8e334b573b4231f58f9798be83178f23ea53635
  USAGE.md: 0b9cb75a3d5c32c1a9c61432f69485f5c5ccf41d
  examples/README.md: bd779bff34653547069d6a647346fc703f8fcfb9
  examples/summary.yaml: 58c12ffc5107dc53f02ed7c04f903fa945d9ec91
  mcps/CREATING.md: 9d426fb29d822f8da53da1f3bd3580f7ba770671
  mcps/README.md: c644840aff1dd2157ca287e6329a93661e2e17b8
  mcps/mcp-ch.yaml: 4f9c7c4529904a68cfe59bdc402b418d5b43ff0c
  mcps/mcp-db.yaml: aae81e65ae3543e5d54ee37cd55d0c13dc6e4c14
  mcps/mcp-email.yaml: be679552b6250f0055f207184ac7b1e178e1b348
  mcps/mcp-file.yaml: 995249f68f27578648a6ced34957b872b62cd6e7
  mcps/mcp-fin.yaml: 919e509a174ba2fec50a1f6066ce57654d179244
  mcps/mcp-kube.yaml: 431dde2e8a85f813f8c42e7d32d6c6582b719057
  mcps/mcp-net.yaml: dff5115d164807f71c61f9ff153e96553144e6a9
  mcps/mcp-oaf.yaml: 5495533600957931871ef9549e3a9cf16609c959
  mcps/mcp-oafp.yaml: 4e7ba7a9ca5cb3dc9faa456f0f58225c7a41602a
  mcps/mcp-random.yaml: ac2ee99722a6ae2baeb14e19d4f881ce03e369c4
  mcps/mcp-rss.yaml: dc1af03277d24234a9440e94c440c9c5b465dc1c
  mcps/mcp-s3.yaml: 845a363c5ca9d291a1ab24dad80972b6651b1a29
  mcps/mcp-shell.yaml: ce8b702efa515b704720f0d4e73a0093c1e4b699
  mcps/mcp-ssh.yaml: 06f3c50811f9cf23e9442f62fad59a8ebdfcd1c9
  mcps/mcp-time.yaml: 5b75f2b73f7650f778f1e80309ba922b006c04f2
  mcps/mcp-weather.yaml: dd339672ebcd6094e8f2ef87fc32a6d95b53bc68
  mini-a-file-tool.js: 583454ffc176c3428319f577f860329524e8a6c2
  mini-a-main.yaml: 81cc2029c4dd67d15f283cb4be0ee09e66db3a54
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: 6a7006d440b40c0c034e0adeaa9d5bb361426749
  mini-a.js: 640ab3ea5a21feb063918a755afd66de575ca0ab
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: 7dccc44f4acd266646770b81aa29832a7b04bcaa
  public/index.md: 0bf7bdc72c67f94edba299201e06e4c0376d6c83
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
  tests/advancedPlanning.js: a6a8d03e4ebaaea66bfa5b61e5daf702f4909f6a
  tests/advancedPlanning.yaml: 9c8f4dcb3d3bba1eda4343dfe7eda1b80126f78b
  tests/autoTestAll.allJobs.yaml: 628921dcb7e35c58e8807cfcbaece93b60ce93ff
  tests/autoTestAll.yaml: f4d909c00e8dbbf507bb6341bf46dd2ceb6ea93d
  tests/coreFunctionality.js: b10c42a85394f0ad6f72cebcef540497349080d8
  tests/coreFunctionality.yaml: 0a656733b02a5a4f77139766e42eabddfc4a39ca
