author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = args.OPACK_PATH

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  To get started, run:")
    print(`     ${path}/mini-a.sh -jobhelp`)
    print("     (and set OAF_MODEL environment variable)")
    print()
    print("  Or set OAF_MODEL environment variable and then start the web interface with:")
    print(`     ${path}/mini-a-web.sh onport=12345`)
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: ''
license: Apache 2.0 license
version: '20251009'
dependencies:
  openaf: '>=20250915'
files:
- .odoc.db
- .package.yaml
- AGENTS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- USAGE.md
- mcps/CREATING.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-kube.yaml
- mcps/mcp-net.yaml
- mcps/mcp-oaf.yaml
- mcps/mcp-ssh.yaml
- mcps/mcp-time.yaml
- mini-a-web.sh
- mini-a-web.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
filesHash:
  .odoc.db: 3dc919db673f13b80bea6d08e8c48ef4e1c5589d
  AGENTS.md: 7b6df1520b27dc3ef4e025a084452c62d0e1c1f9
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: 279d907bcbdcddf93716e208b90b683e53b9f83a
  EXTERNAL-MCPS.md: 49d0ee395b8fb6f06b59b848665ec34f524697f5
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 65b5ca638e2cdefd90c67bd51aade9d3e3241672
  USAGE.md: 55bc427f1b48aaeca3c4eb97e199a3a343e91954
  mcps/CREATING.md: 8d2e251c409148f2178f84dba0ba1bc36f721857
  mcps/README.md: da97b1018bf8cc93515a3ab4836ef77e0a4ca4e4
  mcps/mcp-ch.yaml: 99ae055319e5c99e42cfacead2159b5ed83c1bdc
  mcps/mcp-db.yaml: aaabdae6846d1a8aa62942ab0257dedd9942544d
  mcps/mcp-email.yaml: d9dde29b03e7b8873f66a22476dc8ffd6619ce85
  mcps/mcp-kube.yaml: d9268fd33f64db8afc6a7012540a72a358ccc021
  mcps/mcp-net.yaml: e8fb65fd88862dc4704049f95d1a48f5dffd2251
  mcps/mcp-oaf.yaml: 5495533600957931871ef9549e3a9cf16609c959
  mcps/mcp-ssh.yaml: 06f3c50811f9cf23e9442f62fad59a8ebdfcd1c9
  mcps/mcp-time.yaml: 5b75f2b73f7650f778f1e80309ba922b006c04f2
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: 371733efa9e858952c67a668a52c195f09b18d4d
  mini-a.js: fe2c7a4fba57c4b6a3e7333a82f420ea8f8745a8
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: d95feb44dc8f816d02be99cdce4d1fc4328a9426
  public/index.md: fb0bb5c316bedad82c31cf94ff4498b34719bcce
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
