author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = getOPackPath("mini-a")

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  To get started, run:")
    print(`     ${path}/mini-a.sh -jobhelp`)
    print("     (and set OAF_MODEL environment variable)")
    print()
    print("  Or set OAF_MODEL environment variable and then start the web interface with:")
    print(`     ${path}/mini-a-web.sh onport=12345`)
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: ''
license: Apache 2.0 license
version: '20250927'
dependencies:
  openaf: '>=20250915'
files:
- .odoc.db
- .package.yaml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- USAGE.md
- mcps/CREATING.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-net.yaml
- mcps/mcp-ssh.yaml
- mini-a-web.sh
- mini-a-web.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
filesHash:
  .odoc.db: 3dc919db673f13b80bea6d08e8c48ef4e1c5589d
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: 279d907bcbdcddf93716e208b90b683e53b9f83a
  EXTERNAL-MCPS.md: 1478aed7370e6ce21e1f29f8bee1c816a9c4825b
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: ae38a0dbfab6df6dcacce7fbb630e46063e9574e
  USAGE.md: 6308f0a4450cfac35134690400f18fb4190fe013
  mcps/CREATING.md: 8d2e251c409148f2178f84dba0ba1bc36f721857
  mcps/README.md: bad3f4c6e9e78e4688712fb10a3a343c46314e04
  mcps/mcp-ch.yaml: b831478763c36037a61af095c4be0c4ac2464cec
  mcps/mcp-db.yaml: d2fa8ffe251521e4c4ec42e47fa6ad2de40bc50b
  mcps/mcp-email.yaml: 128fae9e958038e47045242c5752be76da4ec80a
  mcps/mcp-net.yaml: 7b9263f3746916cf35eca7422c2652ce55e13ae4
  mcps/mcp-ssh.yaml: 9933fa7fcc844cf4ace6da2dd3e76ffd4894830d
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: 5ee6f18c11879c597c6a54af160e991ef9469977
  mini-a.js: 82715c336463d9135dfdc6dbdc63c1bbe95bf445
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: 58660229a6450b45f3b85c3ef85be291ab0d08a4
  public/index.md: a6f27b6127f20d08397ae11dd5965c0e47f733ec
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
