author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = getOPackPath("mini-a")

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  To get started, run:")
    print(`     ${path}/mini-a.sh -jobhelp`)
    print("     (and set OAF_MODEL environment variable)")
    print()
    print("  Or set OAF_MODEL environment variable and then start the web interface with:")
    print(`     ${path}/mini-a-web.sh onport=12345`)
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: ''
license: Apache 2.0 license
version: '20250930'
dependencies:
  openaf: '>=20250915'
files:
- .odoc.db
- .package.yaml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- USAGE.md
- mcps/CREATING.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-net.yaml
- mcps/mcp-oaf.yaml
- mcps/mcp-ssh.yaml
- mini-a-web.sh
- mini-a-web.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
filesHash:
  .odoc.db: 3dc919db673f13b80bea6d08e8c48ef4e1c5589d
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: 279d907bcbdcddf93716e208b90b683e53b9f83a
  EXTERNAL-MCPS.md: 49d0ee395b8fb6f06b59b848665ec34f524697f5
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 428e2bfba3d94e32f6d2f2a4ec35c5982084ced3
  USAGE.md: f7ce7e323f5299bef2bdd80b98fe0582a425eadd
  mcps/CREATING.md: 8d2e251c409148f2178f84dba0ba1bc36f721857
  mcps/README.md: 9a74a5fa1885ba353f491aee511978bd77040dec
  mcps/mcp-ch.yaml: b831478763c36037a61af095c4be0c4ac2464cec
  mcps/mcp-db.yaml: d2fa8ffe251521e4c4ec42e47fa6ad2de40bc50b
  mcps/mcp-email.yaml: 128fae9e958038e47045242c5752be76da4ec80a
  mcps/mcp-net.yaml: 7b9263f3746916cf35eca7422c2652ce55e13ae4
  mcps/mcp-oaf.yaml: 1ed1908de8f90b07a66cd83c2483c1955f1a4dd4
  mcps/mcp-ssh.yaml: d47262e5c38b39f2714cb5cf1b4f3d09e92ebed6
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: a37326f35ea403a000cf6a8fc872fb5f7dd8a054
  mini-a.js: 887d3770c918539b5535fba8950fe67ba49b0c41
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: 8be80aa9c87f52512ee511442c20e93d2d55197f
  public/index.md: 5270b3f9b85102767d411a8843ad282c91ede323
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
