author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = args.OPACK_PATH

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  1) Set the OAF_MODEL environment variable.")
    print("     If you need an interactive helper, run:")
    print("       ojob ojob.io/ai/buildOAFModel")
    print()
    print("  2) CLI usage/help:")
    print("       opack exec mini-a -jobhelp")
    print()
    print("  3) Web interface:")
    print("       opack exec mini-a onport=12345 [arguments]")
    print()
    print(`  4) Examples (oJob-based orchestration): ${path}/examples`)
    print()
    print("  5) Optional Unix alias 'mini-a' to run opack exec mini-a:")
    print("       Bash: echo 'alias mini-a=\"opack exec mini-a\"' >> ~/.bashrc && . ~/.bashrc")
    print("       Zsh:  echo 'alias mini-a=\"opack exec mini-a\"' >> ~/.zshrc && . ~/.zshrc")
    print("     Or create a portable wrapper:")
    print("       mkdir -p ~/.local/bin && printf '#!/usr/bin/env sh\\nopack exec mini-a \"$@\"\\n' > ~/.local/bin/mini-a && chmod +x ~/.local/bin/mini-a")
    print("       Ensure ~/.local/bin is on your PATH")
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: ''
mainJob: mini-a-main.yaml
license: Apache 2.0 license
version: '20251104'
dependencies:
  openaf: '>=20250915'
files:
- .odoc.db
- .package.yaml
- AGENTS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- EXTERNAL-MCPS.md
- LICENSE
- README.md
- TESTS_MODELS.md
- USAGE.md
- examples/README.md
- examples/changelog-gen.yaml
- examples/document.yaml
- examples/summary.yaml
- mcps/CREATING.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-file.yaml
- mcps/mcp-fin.yaml
- mcps/mcp-kube.yaml
- mcps/mcp-mini-a.yaml
- mcps/mcp-net.yaml
- mcps/mcp-oaf.yaml
- mcps/mcp-oafp.yaml
- mcps/mcp-random.yaml
- mcps/mcp-rss.yaml
- mcps/mcp-s3.yaml
- mcps/mcp-shell.yaml
- mcps/mcp-ssh.yaml
- mcps/mcp-time.yaml
- mcps/mcp-weather.yaml
- mcps/mcp-web.yaml
- mini-a-con.js
- mini-a-file-tool.js
- mini-a-main.yaml
- mini-a-modes.yaml
- mini-a-web.sh
- mini-a-web.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
- tests/advancedPlanning.js
- tests/advancedPlanning.yaml
- tests/autoTestAll.allJobs.yaml
- tests/autoTestAll.yaml
- tests/coreFunctionality.js
- tests/coreFunctionality.yaml
filesHash:
  .odoc.db: c34866edd2a38fc05b81884dbdd56e083959f65a
  AGENTS.md: 8fb8ca99dbc0f0c11ef55ba7b5edd37666f47a8f
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: d363719aece9628552ff5b49a10d88f896ac5bdf
  EXTERNAL-MCPS.md: f64fa184aa34261b36e4182c785788437e5ee209
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 65c8124b181bffe6cce2b7a98674876320ada15c
  TESTS_MODELS.md: 8c09f3ca8112e4b8bd007fc096fcac8946d25cf7
  USAGE.md: b7de0a6d485f8511d9edb756bc181e2568276b16
  examples/README.md: 0d77434a52d4b21fdd033d980086fa530964e9d8
  examples/changelog-gen.yaml: 4f329832fb682821b7357c5f0a2d4f5f811d29f7
  examples/document.yaml: 19871e428a840eb2b726a4167664a0f27926a66d
  examples/summary.yaml: 335a9a581b5bb0561b2d5db19d39f04830f31209
  mcps/CREATING.md: 9d426fb29d822f8da53da1f3bd3580f7ba770671
  mcps/README.md: cdf68c5b9b999347d5d28aed2c0345a6dc9130b8
  mcps/mcp-ch.yaml: 4f9c7c4529904a68cfe59bdc402b418d5b43ff0c
  mcps/mcp-db.yaml: aae81e65ae3543e5d54ee37cd55d0c13dc6e4c14
  mcps/mcp-email.yaml: be679552b6250f0055f207184ac7b1e178e1b348
  mcps/mcp-file.yaml: 995249f68f27578648a6ced34957b872b62cd6e7
  mcps/mcp-fin.yaml: 919e509a174ba2fec50a1f6066ce57654d179244
  mcps/mcp-kube.yaml: 431dde2e8a85f813f8c42e7d32d6c6582b719057
  mcps/mcp-mini-a.yaml: 205a9413583317addabd6499a6f874d3886fc2da
  mcps/mcp-net.yaml: dff5115d164807f71c61f9ff153e96553144e6a9
  mcps/mcp-oaf.yaml: 5495533600957931871ef9549e3a9cf16609c959
  mcps/mcp-oafp.yaml: 4e7ba7a9ca5cb3dc9faa456f0f58225c7a41602a
  mcps/mcp-random.yaml: ac2ee99722a6ae2baeb14e19d4f881ce03e369c4
  mcps/mcp-rss.yaml: 2f24b8d05aa184b08a23f2ab1789dbf4d2b78581
  mcps/mcp-s3.yaml: 845a363c5ca9d291a1ab24dad80972b6651b1a29
  mcps/mcp-shell.yaml: ce8b702efa515b704720f0d4e73a0093c1e4b699
  mcps/mcp-ssh.yaml: 06f3c50811f9cf23e9442f62fad59a8ebdfcd1c9
  mcps/mcp-time.yaml: 5b75f2b73f7650f778f1e80309ba922b006c04f2
  mcps/mcp-weather.yaml: dd339672ebcd6094e8f2ef87fc32a6d95b53bc68
  mcps/mcp-web.yaml: 9d6b5c89689426419f2f3aaf36b925aa7bbaa732
  mini-a-con.js: ae0c737aff07c8580627d08a488c02098b7ed27b
  mini-a-file-tool.js: 583454ffc176c3428319f577f860329524e8a6c2
  mini-a-main.yaml: 40f2f73ae9f35f8a131b8abe4d72dde980ed3aab
  mini-a-modes.yaml: d148e52565d727674fe636994ec3847b06b3a7aa
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: f6818685e787c378bdb6cb2eb71a87a71989892f
  mini-a.js: 02c5578ce4c46334d371c570061ad91dbc26b1b9
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: b549d80dbddf9028e55c5f880ecb461463e72ae0
  public/index.md: 0bf7bdc72c67f94edba299201e06e4c0376d6c83
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
  tests/advancedPlanning.js: a6a8d03e4ebaaea66bfa5b61e5daf702f4909f6a
  tests/advancedPlanning.yaml: 9c8f4dcb3d3bba1eda4343dfe7eda1b80126f78b
  tests/autoTestAll.allJobs.yaml: 628921dcb7e35c58e8807cfcbaece93b60ce93ff
  tests/autoTestAll.yaml: f4d909c00e8dbbf507bb6341bf46dd2ceb6ea93d
  tests/coreFunctionality.js: b10c42a85394f0ad6f72cebcef540497349080d8
  tests/coreFunctionality.yaml: 0a656733b02a5a4f77139766e42eabddfc4a39ca
