author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: |
    var path = args.OPACK_PATH

    $sh(`chmod +x ${path}/mini-a.sh`)
    .sh(`chmod +x ${path}/mini-a-web.sh`)
    .exec()

    print("Using Mini-A")
    print("------------")
    print()
    print("  1) Set the OAF_MODEL environment variable.")
    print("     If you need an interactive helper, run:")
    print("       ojob ojob.io/ai/buildOAFModel")
    print()
    print("  2) CLI usage/help:")
    print("       opack exec mini-a -jobhelp")
    print()
    print("  3) Web interface:")
    print("       opack exec mini-a onport=12345 [arguments]")
    print()
    print(`  4) Examples (oJob-based orchestration): ${path}/examples`)
    print()
    print("  5) Optional Unix alias 'mini-a' to run opack exec mini-a:")
    print("       Bash: echo 'alias mini-a=\"opack exec mini-a\"' >> ~/.bashrc && . ~/.bashrc")
    print("       Zsh:  echo 'alias mini-a=\"opack exec mini-a\"' >> ~/.zshrc && . ~/.zshrc")
    print("       sh:   echo 'alias mini-a=\"opack exec mini-a\"' >> ~/.profile && . ~/.profile")
    print("     Or create a portable wrapper:")
    print("       mkdir -p ~/.local/bin && printf '#!/usr/bin/env sh\\nopack exec mini-a \"$@\"\\n' > ~/.local/bin/mini-a && chmod +x ~/.local/bin/mini-a")
    print("       Ensure ~/.local/bin is on your PATH")
    print()
    print("Visit https://github.com/openaf/mini-a for documentation and examples.")
    print()
keywords:
- agent
- mini-a
- ai
- llm
- gpt
- mcp
bugs:
  url: https://github.com/OpenAF/mini-a/issues
repository:
  type: http
  url: https://openaf.io/opacks/mini-a.opack
description: Mini-A is a minimalist autonomous agent that uses LLMs, shell commands and/or MCP stdio or http(s) servers to achieve user-defined goals. It is designed to be simple, flexible, and easy to use.
name: mini-a
main: mini-a-con.js
mainJob: ''
license: Apache 2.0 license
version: '20260216'
dependencies:
  openaf: '>=20250915'
files:
- .odoc.db
- .package.yaml
- AGENTS.md
- CHEATSHEET.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- USAGE.md
- docs/BACKEND-ENDPOINTS.md
- docs/DELEGATION.md
- docs/LEARN.md
- docs/MCPPROXY-FEATURE.md
- docs/OPTIMIZATIONS.md
- docs/TESTS_MODELS.md
- docs/WHATS-NEW.md
- examples/README.md
- examples/changelog-gen.yaml
- examples/document.yaml
- examples/learn-from-chat.yaml
- examples/planning-demo.sh
- examples/summary.yaml
- mcps/CREATING.md
- mcps/EXTERNAL-MCPS.md
- mcps/README.md
- mcps/mcp-ch.yaml
- mcps/mcp-db.yaml
- mcps/mcp-email.yaml
- mcps/mcp-file.yaml
- mcps/mcp-fin.yaml
- mcps/mcp-kube.yaml
- mcps/mcp-math.yaml
- mcps/mcp-mini-a.yaml
- mcps/mcp-net.yaml
- mcps/mcp-oaf.yaml
- mcps/mcp-oafp.yaml
- mcps/mcp-office.yaml
- mcps/mcp-proxy.yaml
- mcps/mcp-random.yaml
- mcps/mcp-rss.yaml
- mcps/mcp-s3.yaml
- mcps/mcp-shell.yaml
- mcps/mcp-ssh.yaml
- mcps/mcp-telco.yaml
- mcps/mcp-time.yaml
- mcps/mcp-weather.yaml
- mcps/mcp-web.yaml
- mini-a-con.js
- mini-a-mcptest.js
- mini-a-modelman.js
- mini-a-modes.yaml
- mini-a-subtask.js
- mini-a-utils.js
- mini-a-web.sh
- mini-a-web.yaml
- mini-a-worker.yaml
- mini-a.js
- mini-a.sh
- mini-a.yaml
- public/index.md
- public/showdown.min.js
- tests/advancedPlanning.js
- tests/advancedPlanning.yaml
- tests/autoTestAll.allJobs.yaml
- tests/autoTestAll.yaml
- tests/coreFunctionality.js
- tests/coreFunctionality.yaml
- tests/miniAUtils.js
- tests/miniAUtils.yaml
filesHash:
  .odoc.db: c34866edd2a38fc05b81884dbdd56e083959f65a
  AGENTS.md: e0ab84ff91aaf2057fbbc3ceb8740a215b9002b5
  CHEATSHEET.md: 4cd99ffb88af7aa3b6f811ae6e2051da8b98d591
  CODE_OF_CONDUCT.md: 727a666bab2c5aaf18086b12026a14e3cf77615b
  CONTRIBUTING.md: d363719aece9628552ff5b49a10d88f896ac5bdf
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 4b983bf0fa8ada7d23926c30749e70be082d3d37
  USAGE.md: 25488cec501bd9ffac0ada4b83417a142c506a84
  docs/BACKEND-ENDPOINTS.md: a7fb28ac82a1a05960b995db60f2ce210a2b3b1b
  docs/DELEGATION.md: 59c81b7209ff4d3438a3ba11cf6a27ce92d8dd4e
  docs/LEARN.md: 5f2397d999322fd896be80ee2dddeec90bbf069c
  docs/MCPPROXY-FEATURE.md: a168f177ef3b631cedb78daf5e8138c3261dc3a4
  docs/OPTIMIZATIONS.md: 824fc6755b7572c99ec200b82a423c66d8245fcc
  docs/TESTS_MODELS.md: 29800ca499350bc0eae8ced2bf0b8cf53256f546
  docs/WHATS-NEW.md: f9d9692a2ddf1b0df4dcb0790b5ffbd67921fffa
  examples/README.md: 0d77434a52d4b21fdd033d980086fa530964e9d8
  examples/changelog-gen.yaml: f00b72ae92cd5da9800bf99c1c963e26d1cd08b5
  examples/document.yaml: 1bdc9956d5b46c751a338770a50d2476d6e33858
  examples/learn-from-chat.yaml: 37d0b1e07559c4853d0ea6c144d462269068a20d
  examples/planning-demo.sh: 05c0ef0a5f2452466a01e80158434de0ed29a9a3
  examples/summary.yaml: 335a9a581b5bb0561b2d5db19d39f04830f31209
  mcps/CREATING.md: 9d426fb29d822f8da53da1f3bd3580f7ba770671
  mcps/EXTERNAL-MCPS.md: 152d0db701bc3ee259d4184f08fdce3ca2b0d332
  mcps/README.md: a49a6edcc852dbaedd034ab788db534be1cc4ae5
  mcps/mcp-ch.yaml: 4f9c7c4529904a68cfe59bdc402b418d5b43ff0c
  mcps/mcp-db.yaml: aae81e65ae3543e5d54ee37cd55d0c13dc6e4c14
  mcps/mcp-email.yaml: be679552b6250f0055f207184ac7b1e178e1b348
  mcps/mcp-file.yaml: 995249f68f27578648a6ced34957b872b62cd6e7
  mcps/mcp-fin.yaml: 919e509a174ba2fec50a1f6066ce57654d179244
  mcps/mcp-kube.yaml: 431dde2e8a85f813f8c42e7d32d6c6582b719057
  mcps/mcp-math.yaml: 60944a11b129d9eca27888ef0ef189b33023a432
  mcps/mcp-mini-a.yaml: c08d0e9ec5e29f37abd7e35b0e9808c7cf95d019
  mcps/mcp-net.yaml: dff5115d164807f71c61f9ff153e96553144e6a9
  mcps/mcp-oaf.yaml: 5495533600957931871ef9549e3a9cf16609c959
  mcps/mcp-oafp.yaml: 53b765ccf2ecd338d3a65ef3f65509bab63b1556
  mcps/mcp-office.yaml: e5c2b9aa612ec98f39c3126322922905d7306b02
  mcps/mcp-proxy.yaml: 05450b1153b07aa22d4cd9aea2299bd620de7a22
  mcps/mcp-random.yaml: ac2ee99722a6ae2baeb14e19d4f881ce03e369c4
  mcps/mcp-rss.yaml: 42413cd8146ce049d9e8aeb82265be23ef17213e
  mcps/mcp-s3.yaml: 845a363c5ca9d291a1ab24dad80972b6651b1a29
  mcps/mcp-shell.yaml: ce8b702efa515b704720f0d4e73a0093c1e4b699
  mcps/mcp-ssh.yaml: 06f3c50811f9cf23e9442f62fad59a8ebdfcd1c9
  mcps/mcp-telco.yaml: ec228f93cf7bfa9dfe73a2417d45370327463cdb
  mcps/mcp-time.yaml: fd4e494a2d73d5579912ce8c66fcbb3204046917
  mcps/mcp-weather.yaml: dd339672ebcd6094e8f2ef87fc32a6d95b53bc68
  mcps/mcp-web.yaml: a3c9cd4f02b7874f8faa2a097d445e2f2ca451b9
  mini-a-con.js: ec54740009211451640685a7b440eebd2d79ae49
  mini-a-mcptest.js: 276675bf192fc9431f9096e6854714b635ee2c48
  mini-a-modelman.js: 0a370c6136052b77edd66fa0cfe44c2cbab62a68
  mini-a-modes.yaml: c4c6ba29b1ae0ece481430b76f186ea69f08ec23
  mini-a-subtask.js: 70b9a3a4c283a079526461a7edbc4c7f4415d1ff
  mini-a-utils.js: 47c2538cc52001649fd382506007ea96265934ed
  mini-a-web.sh: 31c3f5a5b5cf0b6795f2079ed5821091c48b4184
  mini-a-web.yaml: d3acef42a7511d20d6a8d7e642a628f1913faaaf
  mini-a-worker.yaml: ee301eb7e9af6910780b350ee6a06e89ce47f75e
  mini-a.js: be1fb9f2ae488bb43c1451ef15869ffe84f3b96f
  mini-a.sh: 0b8991af4014610f24260d0db202a2cd9f6e9f33
  mini-a.yaml: 599491245198705d1df93553c2b2f14d703717e6
  public/index.md: 33e9e75086b0eb51c2e7e05c61250e68da210f8b
  public/showdown.min.js: ecd6a073e7584a8f2d8babe895c8a2190776012f
  tests/advancedPlanning.js: 8e0fefd35f96a3dfa4513f8721c31a1f751f25d4
  tests/advancedPlanning.yaml: 9c8f4dcb3d3bba1eda4343dfe7eda1b80126f78b
  tests/autoTestAll.allJobs.yaml: 91055fe5c42a206a0074f4e3b13f587cbc83fd15
  tests/autoTestAll.yaml: f4d909c00e8dbbf507bb6341bf46dd2ceb6ea93d
  tests/coreFunctionality.js: f737379be45b4a2646373d8ab17246667e0df565
  tests/coreFunctionality.yaml: 92eaf0badb30dfe0af189b21256bc80061e6ffde
  tests/miniAUtils.js: c0b71b495381d2685f98aa512747891da29cca0c
  tests/miniAUtils.yaml: ad8b5061a8a0212e703ddfc64a357068934993c9
