const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('public/advanced.js', 'utf8');
const start = source.indexOf('  function activityText(value) {');
const end = source.indexOf("  const toolbar =", start);
const context = vm.createContext({});
vm.runInContext(source.slice(start, end), context);
const text = context.activityText;
assert.equal(text('\x1b[1;38;5;218mHello\x1b[0m'), 'Hello');
assert.equal(text('\x1b[38;2;12;34;56mRGB\x1b[0m'), 'RGB');
assert.equal(text('\x1b[2K\x1b[1GProgress\x1b[?25l'), 'Progress');
assert.equal(text('\x9b32mGreen\x9b0m'), 'Green');
assert.equal(text('\x1b]8;;https://example.com\x1b\\Link\x1b]8;;\x1b\\'), 'Link');
assert.equal(text('\x1b]0;Window title\x07Body'), 'Body');
assert.equal(text('\x1bPignored control data\x1b\\Body'), 'Body');
assert.equal(text('\x1b(BPlain'), 'Plain');
assert.equal(text('\\u001b[31mEscaped\\u001b[0m'), 'Escaped');
assert.equal(text('\\u001b]0;Title\\u0007Body'), 'Body');
const payload = {rows:[{value:'\x1b[32mSuccess\x1b[0m'}],count:2};
assert.equal(text(payload), JSON.stringify({rows:[{value:'Success'}],count:2},null,2));
assert.equal(payload.rows[0].value, '\x1b[32mSuccess\x1b[0m', 'stored payload is unchanged');
assert.equal(text(JSON.stringify(payload)), JSON.stringify({rows:[{value:'Success'}],count:2}), 'serialized payloads are cleaned too');
const plain = '<script>alert(1)</script>\nC:\\temp\\notes\t[31m';
assert.equal(text(plain),plain,'preserve text, whitespace and literal brackets; rendering remains textContent');
assert.equal(text(undefined),undefined);
assert.equal(text(null),'null');
console.log('Advanced ANSI checks passed: colors, terminal controls, links, nested and serialized payloads, and unchanged source data.');
