# Author: Nuno Aguiar
help:
  text: |
    OpenAF oJob example of having Mini-A (mini AI agent) generate a formatted CHANGELOG.md from git commit history.
    The changelog groups commits by type (features, fixes, chores, docs, etc.) and formats them in a clean,
    readable markdown structure following conventional changelog patterns.

ojob:
  logToConsole: true
  opacks      :
  - mini-a

jobsInclude:
- mini-a.yaml

todo:
- Generate CHANGELOG.md

jobs:
# ---------------------------
- name: Generate CHANGELOG.md
  to:
  - (mini-a           ): | #markdown
      Your task is to CREATE a changelog markdown content by analyzing git commit history.

      IMPORTANT: You must EXECUTE commands and WRITE files using the available tools. Do NOT just output code or scripts as text.

      Steps to complete:
      1. USE the shell tool to run git commands to retrieve commits from the last 50 commits or 6 months (whichever is more recent)
      2. PROCESS and classify commits by type using conventional commit prefixes:
         * Breaking Changes (BREAKING:, breaking:, major:)
         * Features (feat:, feature:, add:, new:)
         * Fixes (fix:, bugfix:, bug:, patch:, hotfix:)
         * Documentation (docs:, doc:, documentation:)
         * Chores (chore:, build:, ci:, refactor:, style:, test:)
         * Other (commits without recognized prefixes)
      3. Format each entry as: "- **[short-hash]**: [message] ([date], by [author])"
      4. Group commits by type in the order listed above
      5. Sort commits within each group by date (newest first)
      6. Clean up commit messages by removing type prefixes and truncate messages longer than 100 characters
      7. OUTPUT the exact contents a CHANGELOG.md should have.

      Example output format:
      ```markdown
      # Changelog

      All notable changes to this project will be documented in this file.

      ## Features
      - **abc123**: Add new user authentication module (2024-01-15, by John Doe)

      ## Fixes
      - **def456**: Fix memory leak in data processing (2024-01-14, by Jane Smith)

      ---
      *Generated automatically from git history*
      ```
    ((youare         )): | #markdown
      You are a technical writer AI agent specialized in generating CHANGELOG.md files from git commit history.
      You have access to shell tools and file writing tools. You must USE these tools to perform actions, not just describe or output what should be done.
    ((rules          )): | #markdown
      - ALWAYS use the shell tool to execute git commands - never just output commands as text
      - Use portable git commands that work across all platforms
      - Ensure the output is valid markdown that renders well in GitHub
      - Prioritize accuracy in commit classification
      - If you need to process data or create a script, write it to a temporary file, execute it, then clean up
    ((useshell       )): true
    ((shellbatch     )): true
    ((shellallowpipes)): true
    ((readwrite      )): true
    ((usetools       )): true
    ((outfile        )): CHANGELOG.md
    ((format         )): md
    ((debug          )): false
