# Author: OpenAF Assistant
help:
  text   : A STDIO/HTTP MCP web search and URL fetching server using jsoup
  expects:
  - name     : onport
    desc     : If defined starts a MCP server on the provided port
    example  : "8888"
    mandatory: false
  - name     : readwrite
    desc     : If true, allows mutating HTTP methods in http-request (POST, PUT, PATCH, DELETE)
    example  : "true"
    mandatory: false

todo:
- Init web context
- (if    ): "isDef(args.onport)"
  ((then)):
  - (httpdStart   ): "${onport:-8080}"
  - (httpdHealthz ): "${onport:-8080}"
  - (httpdMetrics ): "${onport:-8080}"
  - (httpdMCP     ): "${onport:-8080}"
    ((description)): &MCPSERVER
      serverInfo:
        name   : mini-a-web
        title  : OpenAF mini-a MCP web search and URL fetching server
        version: 1.0.0

    ((fnsMeta)): &MCPFNSMETA

      web-search:
        name       : web-search
        description: Performs a web search using DuckDuckGo and returns search results with titles, descriptions, and links.
        inputSchema:
          type      : object
          properties:
            query:
              type       : string
              description: The search query to search for.
            limit:
              type       : number
              description: Maximum number of results to return (default 12).
              default    : 12
            searchEngine:
              type       : string
              description: Search engine to use (currently only "duckduckgo" or "ddg" supported).
              default    : duckduckgo
          required: [ query ]
        annotations:
          title         : web-search
          readOnlyHint  : true
          idempotentHint: true

      get-url:
        name       : get-url
        description: Fetches and processes a URL, returning content in different formats (html, basic, text, or map).
        inputSchema:
          type      : object
          properties:
            url:
              type       : string
              description: The URL to fetch.
            style:
              type       : string
              description: Output format - "html" (raw HTML), "basic" (cleaned HTML), "text" (simple text), or "map" (JSON map representation).
              enum       : [ html, basic, text, map ]
              default    : basic
          required: [ url ]
        annotations:
          title         : get-url
          readOnlyHint  : true
          idempotentHint: true

      http-request:
        name       : http-request
        description: Executes HTTP REST requests against a URL and returns the raw $rest response map (GET and HEAD are allowed in read-only mode; POST/PUT/PATCH/DELETE require readwrite=true).
        inputSchema:
          type      : object
          properties:
            url:
              type       : string
              description: The URL to request.
            method:
              type       : string
              description: HTTP method to use. HEAD is supported and does not require readwrite=true.
              enum       : [ GET, HEAD, POST, PUT, PATCH, DELETE ]
              default    : GET
            data:
              type       : object
              description: Optional request payload map for POST, PUT and PATCH methods.
            headers:
              type       : object
              description: Optional request headers map used for non-GET methods.
            throwExceptions:
              type       : boolean
              description: If true, non-2xx responses throw exceptions when using non-GET methods.
              default    : false
          required: [ url ]
        annotations:
          title         : http-request
          readOnlyHint  : false
          idempotentHint: false

    ((fns    )): &MCPFNS
      web-search  : Web search
      get-url     : Get URL
      http-request: HTTP Request

  ((else)):
  - (stdioMCP ): *MCPSERVER
    ((fnsMeta)): *MCPFNSMETA
    ((fns    )): *MCPFNS

ojob:
  opacks      :
  - openaf     : 20250915
  - oJob-common: 20250914
  - Jsoup
  catch       : printErrnl("[" + job.name + "] "); $err(exception, __, __, job.exec)
  logToConsole: false
  argsFromEnvs: true
  daemon      : true
  unique      :
    pidFile     : .mcp-web.pid
    killPrevious: true
  loadLibs    :
  - jsoup.js
  - webSearch.js

include:
- oJobMCP.yaml

init:
  defaultUserAgent: mini-a-mcp-web

jobs:
# -----------------------
- name : Init web context
  check:
    in:
      readwrite: toBoolean.isBoolean.default(false)
  exec : | #js
    global.__webReadWrite__ = args.readwrite === true

# -----------------
- name : Web search
  check:
    in:
      query       : isString
      limit       : toNumber.isNumber.default(12)
      searchEngine: isString.default("duckduckgo")
  exec : | #js
    var ws = new WebSearch()
    return ws.search(args.query, args.limit, args.searchEngine)

# --------------
- name : Get URL
  check:
    in:
      url      : isString
      style    : isString.oneOf([ "html", "basic", "text", "map" ]).default(__)
  exec : | #js
    var _s = $rest().get(args.url)
    if (isDef(args.style)) {
      var ws = new WebSearch()
      return ws.getURL(_s, args.style)
    } else {
      return _s
    }

# -------------------
- name : HTTP Request
  check:
    in:
      url            : isString
      method         : isString.oneOf([ "GET", "HEAD", "POST", "PUT", "PATCH", "DELETE" ]).default("GET")
      data           : isMap.default(__)
      headers        : isMap.default(__)
      throwExceptions: toBoolean.isBoolean.default(false)
  exec : | #js
    var method = String(args.method).toLowerCase()
    if ([ "post", "put", "patch", "delete" ].indexOf(method) >= 0 && !global.__webReadWrite__) {
      return "[ERROR] Read-only mode. Set readwrite=true to allow write operations"
    }

    var r = $rest({
      requestHeaders : args.headers,
      throwExceptions: args.throwExceptions
    })

    switch(method) {
    case "get":
      return r.get(args.url)
    case "head":
      return r.head(args.url)
    case "post":
      return r.post(args.url, _$(args.data, "data").isMap().default({}))
    case "put":
      return r.put(args.url, _$(args.data, "data").isMap().default({}))
    case "patch":
      return r.patch(args.url, _$(args.data, "data").isMap().default({}))
    case "delete":
      return r.delete(args.url)
    default:
      throw "Unsupported HTTP method '" + args.method + "'."
    }
